// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using OpenServices.Entities;
using System;

namespace OpenServices.Migrations
{
    [DbContext(typeof(OpenServicesContext))]
    [Migration("20190407234616_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OpenServices.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cpf");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Nome");

                    b.Property<string>("Rg");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Usuario");
                });

            modelBuilder.Entity("OpenServices.Entities.Cliente", b =>
                {
                    b.HasBaseType("OpenServices.Entities.Usuario");

                    b.Property<string>("Endereco");

                    b.ToTable("Cliente");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("OpenServices.Entities.PrestadorServico", b =>
                {
                    b.HasBaseType("OpenServices.Entities.Usuario");

                    b.Property<string>("Cnpj");

                    b.Property<string>("Especializacao");

                    b.ToTable("PrestadorServico");

                    b.HasDiscriminator().HasValue("PrestadorServico");
                });
#pragma warning restore 612, 618
        }
    }
}
